### ISSUE TITLE
Proximity event broken under jQuery 1.8.0

### ISSUE THREAD

**Issue by ktonini** [padolsey-archive/jquery.fn#18]
it appears as if the proximity location is stuck to the upper left of the target div

**Comment by ktonini** [comment]
Fixed by changing lines 199, and 120 respectively -

```
    right = left + el.width();
    bottom = top + el.height();
```

Just a quick fix though, there's probably a better way.  See http://blog.jquery.com/2012/08/16/jquery-1-8-box-sizing-width-csswidth-and-outerwidth/

**Comment by padolsey** [comment]
I cannot reproduce this breaking with jQuery 1.8. See http://jsbin.com/oxenow/1/ (seems to work fine)

Could you provide code which breaks it?

**Comment by ktonini** [comment]
Hmm, this is what I'm using - 

``` javascript
$('#title').on('proximity', {max: 50, fireOutOfBounds: true}, function(event, proximity, distance){
    $('#titleDots').css('opacity', proximity);
});
```

**Comment by ktonini** [comment]
And here are the css properties on the #title element in case it has something to do with that, although it was behaving the same way on two instances of proximity that I had.

``` css
#title {
text-align: center;
position: relative;
margin-bottom: -45px;
top: 65px;
font-size: 18px;
text-shadow: 0 -4px 4px rgba(0, 0, 0, 0.38), 0 4px 4px rgba(0, 0, 0, 0.38);
letter-spacing: 4px;
height: 45px;
cursor: default;
-webkit-transform: translate3d(0,0,0);
}
```
